### ISSUE TITLE
Deploy to GitHub Pages

### ISSUE THREAD

**Issue by lucylee-412** [maxyedid/Assignment-7-giphy#9]
_Notes: I already set up the scripts and packages on the deploy branch, but it's not working, possibly because I'm not the owner of the repository. I'm going to fork the repository and try it out from my own GitHub account._

If @maxyedid could check out the GitHub Pages tab from the settings for this repository to see if it was configured properly, that'd be great.
Also since it's not my repository, I can't link any of the pull requests so please link the one coming from #8 when you can.

**Comment by lucylee-412** [comment]
Checked it out on my forked repository and I had a network error because of the GIPHY API being loaded over HTTP (same issue I had with the last assignment). Once I changed the link, the site loaded our project without a hitch.

Going to update the links in this repository and see if that makes a difference.

**Comment by lucylee-412** [comment]
So far, nada. Reassigning Max to check it out as the owner of this repository.

**Comment by maxyedid** [comment]
Deployed to github pages
